Always use FQCN for extends_documentation_fragment
bcoca/gravity pull request #15
Opened 2019-08-12 14:28 UTC by mkrizek

2019-08-12 14:42 UTC, webknjaz approved these changes

2019-08-13 12:25 UTC, bcoca requested changes

2019-08-13 12:25 UTC, bcoca commented on migrate.py
>          fragment_collection = get_fragment_collection(fragment, spec)
shouldn't this be 'get_plugin_collection'?

also it is possible there is no collection for the fragment/module_utils so we should not rewrite those

2019-08-13 12:51 UTC, merged

2019-08-13 12:51 UTC, webknjaz approved these changes