Mark migrated files in botmeta
bcoca/gravity pull request #18
Opened 2019-08-13 16:39 UTC by webknjaz

2019-08-13 18:19 UTC, bcoca requested changes

2019-08-13 18:19 UTC, bcoca commented on migrate.py
> +from pathlib import Path
we already discussed this

2019-08-13 18:19 UTC, bcoca commented on migrate.py
> +from ruamel.yaml import YAML
stop adding new deps, just use pyyaml

2019-08-13 21:48 UTC, webknjaz commented on migrate.py
> +from ruamel.yaml import YAML
I can't, it doesn't preserve comments.

2019-08-13 21:48 UTC, webknjaz commented on migrate.py
> +from pathlib import Path
I'm not using slashes as you asked.

2019-08-14 13:53 UTC, webknjaz commented
Diff, produced by ruamel.yaml:
```diff
diff --git a/.github/BOTMETA.yml b/.github/BOTMETA.yml
index bb5ec4b137..28b1a7c5d9 100644
--- a/.github/BOTMETA.yml
+++ b/.github/BOTMETA.yml
@@ -34,7 +34,7 @@
 #           supershipit - supershipiteers can turn a shipit into a supershipit
 #
 
-automerge: True
+automerge: true
 files:
   .github/BOTMETA.yml:
     labels: botmeta
@@ -116,14 +116,14 @@ files:
     maintainers: $team_cloudstack
     labels: cloudstack
   $modules/cloud/digital_ocean/: &digital_ocean
-    keywords: [ digital ocean, droplet ]
-    labels: [ cloud, digital_ocean ]
+    keywords: [digital ocean, droplet]
+    labels: [cloud, digital_ocean]
     maintainers: $team_digital_ocean
     support: community
   $modules/cloud/dimensiondata/dimensiondata_network.py: tintoy
   $modules/cloud/docker/: &docker
     ignored: ThomasSteinbach
-    labels: [ cloud, docker ]
+    labels: [cloud, docker]
     maintainers: $team_docker
     supershipit: felixfontein
   $modules/cloud/docker/docker_compose.py:
@@ -141,29 +141,29 @@ files:
     ignored: supertom
   $modules/cloud/google/gc_storage.py: supertom
   $modules/cloud/hcloud/: &hcloud
-    keywords: [ hcloud, hetzner cloud ]
-    labels: [ cloud, hcloud ]
+    keywords: [hcloud, hetzner cloud]
+    labels: [cloud, hcloud]
     maintainers: $team_hcloud
   $modules/cloud/huawei/: &huawei
-    keywords: [ cloud, huawei, hwc ]
-    labels: [ cloud, huawei ]
+    keywords: [cloud, huawei, hwc]
+    labels: [cloud, huawei]
     maintainers: $team_huawei
   $modules/cloud/kubevirt/: &kubevirt
-    keywords: [ kubevirt ]
-    labels: [ cloud, kubevirt ]
+    keywords: [kubevirt]
+    labels: [cloud, kubevirt]
     maintainers: $team_kubevirt
   $modules/cloud/linode/: $team_linode
   $modules/cloud/lxd/: hnakamur
   $modules/cloud/memset/: glitchcrab
   $modules/cloud/misc/ovirt.py: &ovirt
     ignored: vincentvdk
-    keywords: [ ovirt, RHEV, RHV ]
-    labels: [ cloud, ovirt ]
+    keywords: [ovirt, RHEV, RHV]
+    labels: [cloud, ovirt]
     maintainers: $team_ovirt
   $modules/cloud/misc/proxmox.py: &virt
     ignored: skvidal
-    keywords: [ kvm, libvirt, proxmox, qemu ]
-    labels: [ cloud, virt ]
+    keywords: [kvm, libvirt, proxmox, qemu]
+    labels: [cloud, virt]
     maintainers: $team_virt
   $modules/cloud/misc/proxmox_kvm.py: *virt
   $modules/cloud/misc/proxmox_template.py: *virt
@@ -176,7 +176,7 @@ files:
   $modules/cloud/opennebula/: ilicmilan kustodian xorel rsmontero
   $modules/cloud/openstack/: $team_openstack
   $modules/cloud/oracle/: &oracle
-    labels: [ cloud, oracle ]
+    labels: [cloud, oracle]
     maintainers: $team_oracle
     support: community
   $modules/cloud/ovirt/: *ovirt
@@ -186,19 +186,20 @@ files:
   $modules/cloud/scaleway/scaleway_volume.py:
     ignored: hekonsek
   $modules/cloud/smartos/: &solaris
-    keywords: [ beadm, dladm, illumos, ipadm, nexenta, omnios, openindiana, pfexec, smartos, solaris, sunos, zfs, zpool ]
+    keywords: [beadm, dladm, illumos, ipadm, nexenta, omnios, openindiana, pfexec,
+      smartos, solaris, sunos, zfs, zpool]
     labels: solaris
     maintainers: $team_solaris
   $modules/cloud/univention/: keachi
   $modules/cloud/vmware/: &vmware
     ignored: cigamit jcpowermac mtnbikenc tchernomax ckotte
-    keywords: [ esx, vcenter, vcsa, vcsim, vsphere ]
-    labels: [ cloud, vmware ]
+    keywords: [esx, vcenter, vcsa, vcsim, vsphere]
+    labels: [cloud, vmware]
     maintainers: $team_vmware
     notified: lparkes
   $modules/cloud/vmware/vmware_vm_shell.py: chrrrles
   $modules/cloud/vultr/: &vultr
-    labels: [ cloud, vultr ]
+    labels: [cloud, vultr]
     maintainers: $team_vultr
   $modules/cloud/webfaction/: quentinsf
   $modules/cloud/xenserver/: bvitnik
@@ -212,18 +213,18 @@ files:
   $modules/commands/script.py: $team_ansible
   $modules/commands/shell.py: $team_ansible
   $modules/crypto/: &crypto
-    keywords: [ acme, letsencrypt, lets encrypt, luks, openssl ]
+    keywords: [acme, letsencrypt, lets encrypt, luks, openssl]
     labels: crypto
     maintainers: $team_crypto
     supershipit: felixfontein
   $modules/database/influxdb/: kamsz
   $modules/database/mssql/mssql_db.py: Jmainguy kenichi-ogawa-1988
   $modules/database/mysql/: &mysql
-    keywords: [ mariadb, proxysql ]
-    labels: [ database, mysql ]
+    keywords: [mariadb, proxysql]
+    labels: [database, mysql]
     maintainers: $team_mysql
   $modules/database/postgresql/: &postgresql
-    keywords: [ database, postgres, postgresql ]
+    keywords: [database, postgres, postgresql]
     labels: postgresql
     maintainers: $team_postgresql
     notified: jbscalia
@@ -283,22 +284,22 @@ files:
   $modules/net_tools/nios/:
     maintainers: $team_networking sganesh-infoblox
     labels:
-      - networking
-      - infoblox
+    - networking
+    - infoblox
   $modules/net_tools/netbox/: FragmentedPacket
   $modules/network/a10/: ericchou1 mischapeters
   $modules/network/aci/: &aci
-    keywords: [ aci, cisco msc, cisco mso, multisite, multi-site ]
-    labels: [ aci, cisco, networking ]
+    keywords: [aci, cisco msc, cisco mso, multisite, multi-site]
+    labels: [aci, cisco, networking]
     maintainers: $team_aci
   $modules/network/aireos/: &aireos
     maintainers: $team_aireos
-    labels: [ aireos, cisco, networking ]
+    labels: [aireos, cisco, networking]
   $modules/network/aos/: dgarros jeremyschulman
   $modules/network/aruba/: jmighion
   $modules/network/asa/: &asa
     maintainers: $team_asa
-    labels: [ asa, cisco, networking ]
+    labels: [asa, cisco, networking]
   $modules/network/avi/: $team_avi
   $modules/network/bigswitch/: jayakody tedelhourani vuile
   $modules/network/cloudengine/:
@@ -321,17 +322,17 @@ files:
   $modules/network/fortios/: bjolivot
   $modules/network/fortimanager/: $team_fortimanager
   $modules/network/ftd/: &ftd
-    keywords: [ firepower, ftd ]
-    labels: [ cisco, ftd, networking ]
+    keywords: [firepower, ftd]
+    labels: [cisco, ftd, networking]
     maintainers: $team_ftd
     support: community
   $modules/network/illumos/: *solaris
   $modules/network/interface/: $team_networking
   $modules/network/ios/: &ios
-    labels: [ cisco, ios, networking ]
+    labels: [cisco, ios, networking]
     maintainers: $team_ios
   $modules/network/iosxr/: &iosxr
-    labels: [ cisco, iosxr, networking ]
+    labels: [cisco, iosxr, networking]
     maintainers: $team_iosxr
   $modules/network/ironware/: paulquack
   $modules/network/junos/: Qalthos ganeshrn
@@ -339,7 +340,7 @@ files:
   $modules/network/layer2/: $team_networking
   $modules/network/layer3/: $team_networking
   $modules/network/meraki/: &meraki
-    labels: [ cisco, meraki, networking ]
+    labels: [cisco, meraki, networking]
     maintainers: $team_meraki
   $modules/network/netconf/netconf_config.py: userlerueda $team_networking
   $modules/network/netconf/netconf_get.py: $team_networking
@@ -349,11 +350,11 @@ files:
   $modules/network/nos/: $team_extreme
   $modules/network/nuage/: pdellaert
   $modules/network/nxos/: &nxos
-    keywords: [ nxapi ]
-    labels: [ cisco, networking, nxos ]
+    keywords: [nxapi]
+    labels: [cisco, networking, nxos]
     maintainers: $team_nxos
   $modules/network/nso/: &nso
-    labels: [ cisco, networking, nso ]
+    labels: [cisco, networking, nso]
     maintainers: $team_nso
   $modules/network/onyx/: $team_onyx
   $modules/network/ordnance/: alexanderturner djh00t
@@ -388,18 +389,19 @@ files:
   $modules/packaging/os/apt_repository.py: $team_ansible
   $modules/packaging/os/openbsd_pkg.py: &bsd
     ignored: bleader
-    keywords: [ doas, dragonfly, freebsd, iocage, jail, netbsd, openbsd, opnsense, pfsense ]
+    keywords: [doas, dragonfly, freebsd, iocage, jail, netbsd, openbsd, opnsense,
+      pfsense]
     labels: bsd
     maintainers: $team_bsd
   $modules/packaging/os/homebrew.py: &macos
     ignored: frenck
-    keywords: [ brew, cask, darwin, homebrew, macosx, macports, osx ]
+     [...]

2019-08-14 13:54 UTC, webknjaz commented
Diff, produced by PyYAML:
```diff
diff --git a/.github/BOTMETA.yml b/.github/BOTMETA.yml
index bb5ec4b137..27b82b8720 100644
--- a/.github/BOTMETA.yml
+++ b/.github/BOTMETA.yml
@@ -1,44 +1,7 @@
-# BOTMETA V2.0
-#
-# Data used by ansibot to identify who works on each file in the repo.
-# If you have questions about this data format, please join #ansible-devel
-# on irc.freenode and ping anyone who is op'ed.
-#
-# There are 3 primary sections of the data
-#
-#   automerge
-#       During release freezes, the bot uses this key to know if
-#       automerging should be on or off. It is a boolean value.
-#
-#   macros
-#       Macros are used to shorten and group some strings and lists.
-#       Any macro with a prefix of "team_" is a maintainer group for
-#       various files.
-#
-#   files
-#       Each key represents a specific file in the repository.
-#       If a module is not listed, its maintainers default to the authors.
-#       If the file has no maintainers key, the value of the key is
-#       presumed to be the maintainers.
-#
-#       Keys:
-#           maintainers - these people can shipit and automerge
-#           notified - these people are always subscribed to relevant issues
-#           ignored - these people should never be notified
-#           deprecated - this file is deprecated but probably not yet renamed
-#           keywords - used to identify this file based on the issue description
-#           support - used for files without internal ANSIBLE_METADATA, see
-#                     https://github.com/ansible/ansible/labels?q=support for full list
-#           labels - list of GitHub labels to apply. Path components of 'file' parent key
-#                    which are valid GitHub labels are automatically added.
-#           supershipit - supershipiteers can turn a shipit into a supershipit
-#
-
-automerge: True
+automerge: true
 files:
   .github/BOTMETA.yml:
     labels: botmeta
-    # Changes to BOTMETA MUST always be reviewed by Core Team
     support: core
   changelogs/fragments/:
     support: community
@@ -115,90 +78,149 @@ files:
   $modules/cloud/cloudstack/:
     maintainers: $team_cloudstack
     labels: cloudstack
-  $modules/cloud/digital_ocean/: &digital_ocean
-    keywords: [ digital ocean, droplet ]
-    labels: [ cloud, digital_ocean ]
+  $modules/cloud/digital_ocean/: &id010
+    keywords:
+    - digital ocean
+    - droplet
+    labels:
+    - cloud
+    - digital_ocean
     maintainers: $team_digital_ocean
     support: community
   $modules/cloud/dimensiondata/dimensiondata_network.py: tintoy
-  $modules/cloud/docker/: &docker
+  $modules/cloud/docker/: &id011
     ignored: ThomasSteinbach
-    labels: [ cloud, docker ]
+    labels: &id001
+    - cloud
+    - docker
     maintainers: $team_docker
     supershipit: felixfontein
   $modules/cloud/docker/docker_compose.py:
-    <<: *docker
+    ignored: ThomasSteinbach
+    labels: *id001
     maintainers: $team_docker sluther
+    supershipit: felixfontein
   $modules/cloud/docker/docker_network.py:
-    <<: *docker
+    ignored: ThomasSteinbach
+    labels: *id001
     maintainers: $team_docker olsaki
+    supershipit: felixfontein
   $modules/cloud/docker/docker_swarm_service.py:
-    <<: *docker
+    ignored: ThomasSteinbach
+    labels: *id001
     maintainers: $team_docker hannseman
+    supershipit: felixfontein
   $modules/cloud/google/:
     supershipit: $team_google
     maintainers: $team_google
     ignored: supertom
   $modules/cloud/google/gc_storage.py: supertom
-  $modules/cloud/hcloud/: &hcloud
-    keywords: [ hcloud, hetzner cloud ]
-    labels: [ cloud, hcloud ]
+  $modules/cloud/hcloud/: &id036
+    keywords:
+    - hcloud
+    - hetzner cloud
+    labels:
+    - cloud
+    - hcloud
     maintainers: $team_hcloud
-  $modules/cloud/huawei/: &huawei
-    keywords: [ cloud, huawei, hwc ]
-    labels: [ cloud, huawei ]
+  $modules/cloud/huawei/:
+    keywords: &id016
+    - cloud
+    - huawei
+    - hwc
+    labels:
+    - cloud
+    - huawei
     maintainers: $team_huawei
-  $modules/cloud/kubevirt/: &kubevirt
-    keywords: [ kubevirt ]
-    labels: [ cloud, kubevirt ]
+  $modules/cloud/kubevirt/: &id017
+    keywords:
+    - kubevirt
+    labels:
+    - cloud
+    - kubevirt
     maintainers: $team_kubevirt
   $modules/cloud/linode/: $team_linode
   $modules/cloud/lxd/: hnakamur
   $modules/cloud/memset/: glitchcrab
-  $modules/cloud/misc/ovirt.py: &ovirt
+  $modules/cloud/misc/ovirt.py: &id003
     ignored: vincentvdk
-    keywords: [ ovirt, RHEV, RHV ]
-    labels: [ cloud, ovirt ]
+    keywords:
+    - ovirt
+    - RHEV
+    - RHV
+    labels:
+    - cloud
+    - ovirt
     maintainers: $team_ovirt
-  $modules/cloud/misc/proxmox.py: &virt
+  $modules/cloud/misc/proxmox.py: &id002
     ignored: skvidal
-    keywords: [ kvm, libvirt, proxmox, qemu ]
-    labels: [ cloud, virt ]
+    keywords:
+    - kvm
+    - libvirt
+    - proxmox
+    - qemu
+    labels:
+    - cloud
+    - virt
     maintainers: $team_virt
-  $modules/cloud/misc/proxmox_kvm.py: *virt
-  $modules/cloud/misc/proxmox_template.py: *virt
-  $modules/cloud/misc/rhevm.py: *virt
-  $modules/cloud/misc/virt.py: *virt
-  $modules/cloud/misc/virt_net.py: *virt
-  $modules/cloud/misc/virt_pool.py: *virt
+  $modules/cloud/misc/proxmox_kvm.py: *id002
+  $modules/cloud/misc/proxmox_template.py: *id002
+  $modules/cloud/misc/rhevm.py: *id002
+  $modules/cloud/misc/virt.py: *id002
+  $modules/cloud/misc/virt_net.py: *id002
+  $modules/cloud/misc/virt_pool.py: *id002
   $modules/cloud/misc/xenserver_facts.py:
     ignored: andyhky
   $modules/cloud/opennebula/: ilicmilan kustodian xorel rsmontero
   $modules/cloud/openstack/: $team_openstack
-  $modules/cloud/oracle/: &oracle
-    labels: [ cloud, oracle ]
+  $modules/cloud/oracle/: &id028
+    labels:
+    - cloud
+    - oracle
     maintainers: $team_oracle
     support: community
-  $modules/cloud/ovirt/: *ovirt
+  $modules/cloud/ovirt/: *id003
   $modules/cloud/profitbricks/: baldwinSPC
   $modules/cloud/rackspace/:
     ignored: sivel angstwad
   $modules/cloud/scaleway/scaleway_volume.py:
     ignored: hekonsek
-  $modules/cloud/smartos/: &solaris
-    keywords: [ beadm, dladm, illumos, ipadm, nexenta, omnios, openindiana, pfexec, smartos, solaris, sunos, zfs, zpool ]
+  $modules/cloud/smartos/: &id005
+    keywords:
+    - beadm
+    - dladm
+    - illumos
+    - ipadm
+    - nexenta
+    - omnios
+    - openindiana
+    - pfexec
+    - smartos
+    - solaris
+    - sunos
+    - zfs
+    - zpool
     labels: solaris
     maintainers: $team_solaris
   $modules/cloud/univention/: keachi
-  $modules/cloud/vmware/: &vmware
+  $modules/cloud/vmware/: &id033
     ignored: cigamit jcpowermac mtnbikenc tchernomax ckotte
-    keywords: [ esx, vcenter, vcsa, vcsim, vsphere ]
-    labels: [ cloud, vmware ]
+    keywords:
+    - esx
+    - vcenter
+    - vcsa
+    - vcsim
+    - vsphere
+    labels:
+    - cloud
+    - vmware
     maintainers: $team_vmware
     notified: lparkes
   $modules/cloud/vmware/vmware_vm_shell.py: chrrrles
-  $modules/cloud/vultr/: &vultr
-    labels: [ cloud, vultr ]
+  $modules/cloud/vultr/: &id034
+    labels:
+    - cloud
+    - vultr
     maintainers: $team_vultr
   $modules/cloud/webfaction/: quentinsf
   $modules/cloud/xenserver/: bvitnik
@@ -211,23 +233,35 @@ files:
   $modules/commands/raw.py: $team_ansible
   $modules/commands/script.py: $team_ansible
   $modules/commands/shell.py: $team_ansible
-  $modules/crypto/: &crypto
-    keywords: [ acme, letsencrypt, lets encrypt, luks, openssl ]
+  $modules/crypto/: &id012
+    keywords:
+    - acme
+    - letsencrypt
+    - lets encrypt
+    - luks
+    - openssl
     labels: crypto
     maintainers: $team_crypto
     supershipit: felixfontein
   $modules/database/influxdb/: kamsz
   $modules/database/mssql/mssql_db.py: Jmainguy kenichi-ogawa-1988
-  $modules/database/mysql/: &mysql
-    keywords: [ mariadb, proxysql ]
-    labels: [ database, mysql ]
+  $m [...]

2019-08-14 18:03 UTC, merged